repos:
- repo: https://github.com/codespell-project/codespell
  rev: v2.2.4
  hooks:
  - id: codespell
    additional_dependencies: [tomli]
    # args: ["--write-changes"]  # consider enabling for auto-fif
    exclude: "test/fixtures/"

- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: v0.4.3
  hooks:
  - id: ruff
    args: ["--fix"]
    exclude: ^git/ext/
  - id: ruff-format
    exclude: ^git/ext/

- repo: https://github.com/shellcheck-py/shellcheck-py
  rev: v0.9.0.6
  hooks:
  - id: shellcheck
    args: [--color]
    exclude: ^test/fixtures/polyglot$|^git/ext/

- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.5.0
  hooks:
  - id: end-of-file-fixer
    exclude: test/fixtures/
  - id: check-toml
  - id: check-yaml
  - id: check-merge-conflict

- repo: https://github.com/abravalheri/validate-pyproject
  rev: v0.16
  hooks:
    - id: validate-pyproject
